CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL AUTO_INCREMENT PRIMARY KEY,
    social VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(50),
    discord_user VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);